### ISSUE TITLE
Inconsistent arithmetic

### ISSUE THREAD

**Issue by vks** [murarth/ketos#13]
```
ketos=> (+)
0
ketos=> (+ 1)
1
ketos=> (-)
compile error: `-` expected at least 1 argument; found 0
ketos=> (- 1)
-1
ketos=> (*)
1
ketos=> (* 1)
1
ketos=> (/)
compile error: `/` expected at least 1 argument; found 0
ketos=> (/ 1)
1/1
```

I would expect the following evaluations:

```
ketos=> (-)
0
ketos=> (/)
1
ketos=> (/ 1)
1
```

**Comment by murarth** [comment]
Okay, there are two issues here that I want to address separately:

1. The functions `-` and `/` require at least one argument, while `+` and `*` do not.
2. `(/ 1)` returns `1/1`.

The first issue, I'm admittedly hazy about. The Ketos implementation of these functions is simply based on the behavior of the Lisp dialect implementations that I used somewhat as reference during development -- GNU CLISP and scheme48 both require one or more arguments for `-` and `/`, but not for `+` and `*`. It's quite possible that the reasoning for this is specific only to the implementation of these Lisp dialects. I don't know that I have a good reason for favoring either behavior over the other.

I suppose the only time it really matters is when using `(apply op numbers)`. For `+`, this intuitively means "give me the sum of these numbers." And an empty list, naturally, results in a sum of `0`. But what is one really asking for if they use `(apply - numbers)`? And what should they expect in the case of an empty list? If this is not as fleshed out a concept as calculating sum, perhaps it should continue to be treated as an error.

As for the second issue, I'm not sure whether you're suggesting that `(/ n)` should return `n` or that it should not convert `1` into a ratio. If the former, I would point out that that this is consistent with `(- n)` being equivalent to `(- 0 n)`. If the latter, you are correct that `(/ 1 1)` returns `1` instead of `1/1` and that `(/ 1)` should do the same. I've now pushed a fix to this.

**Comment by vks** [comment]
To me it does not make mathematically sense that `-` and `+` behave differently. `a - b` is short for `a + (-b)` after all. The same applies to `/`, `a / b` is short for `a * 1/b`.

However, it seems that the current behavior is in line with many lisp dialects (I tried clisp and racket).

For the second one issue I meant it like you said (`(/ 1)` should be equivalent to `(/ 1 1)`).

**Comment by murarth** [comment]
But you've just outlined the meaningful difference between these functions. `-` and `/` treat arguments after the first differently than the first argument. Therefore, the functions can be thought of as applying a particular transformation to the first argument, using the successive arguments. This is in contrast to `+` and `*` conceptually operating on a set of values.

**Comment by vks** [comment]
Fair enough. I think everything is consistent now then. :)
