### ISSUE TITLE
Allow Global Scope clone

### ISSUE THREAD

**Issue by mrapogee** [murarth/ketos#22]
It is possible to allow cloning of the global scope?

I have a server that receives many requests, I want to be able to execute code from a base scope from each request, without values or macros defined in any given request leaking into the global scope.

**Comment by murarth** [comment]
I don't think implementing `Clone` for `GlobalScope` is a great idea. It could be confused with cloning the `Rc` handle and it may not be clear that cloning the scope itself still shares some data (some internal `GlobalScope` fields are themselves `Rc`).

If you want to share the `Rc` fields, you can use [`GlobalScope::new_using`](https://docs.rs/ketos/0.3.0/ketos/scope/struct.GlobalScope.html#method.new_using) to create a new `Scope`. Otherwise, you might want to create a new global scope with new data fields.

**Comment by mrapogee** [comment]
Cloning with new_using does nothing for me. As far as I have tested, this doesn't actually copy the scope with the values injected into it, it just copies the io and the module loader.

The only way I can inject macros, etc. into a scope right now, is to re-compile the macros from source every time I want to run a script.

What I'm asking is there any way to take a scope with everything it contains, and cleanly create a new scope with those values + macros so that I can run code in it without effecting the original scope.

It doesn't need to be the actual clone trait.

**Comment by mrapogee** [comment]
From what I can see in the source, I need to be able to clone the actual `Namespace`

**Comment by murarth** [comment]
Oh, I didn't realize that you *did* want values in the base scope to be cloned. A clone-like method does seem to be the clearest way of allowing this.

I've just pushed a commit adding the method `GlobalScope::clone_scope`. I'll publish to Cargo (under version 0.3.1) once it passes CI.

**Comment by murarth** [comment]
Published.

**Comment by mrapogee** [comment]
Awesome!!! Thanks!
