### ISSUE TITLE
Cannot insert variable into global scope from within `let`.

### ISSUE THREAD

**Issue by Wulfsta** [murarth/ketos#30]
Attempting to use define to insert a variable into the global scope from within a `let` statement throws an error. A minimal example to demonstrate
```
extern crate ketos;

use ketos::{Interpreter, FromValue};

fn main() {
    let interp = Interpreter::new();

    match interp.run_code(r#"
        (let ((plus +) (mult *)) (
            (define ten (mult (plus 3 2) 2))
        ))
        "#, None) {
        Ok(k) => k,
        Err(e) => panic!(interp.display_error(&e)),
    };

    let m = i32::from_value(interp.get_value("ten").unwrap()).unwrap();

    println!("{}", m);
}
```
will throw
```
execution error: type error: expected function; found name: ten
```

In contrast, if we change the Ketos code executed to 
```
...
match interp.run_code(r#"
    (define ten (* (+ 3 2) 2))
"#, None) {
...
```
this code executes without error, printing `10`.

**Comment by murarth** [comment]
This one had me confused for a bit. I didn't see the issue right away.

The problem is that you're placing extra parentheses around the body of `let`. This becomes clearer if you use the traditional indentation style.

```lisp
(let ((plus +) (mult *))
     ((define ten (mult (plus 3 2) 2))))
```

Double parentheses around `(define ...)` means that the `define` operator is processed, then an attempt is made to execute the result (which is the name of the definition). Remove the extra parentheses and it executes just fine:

```lisp
ketos=> (let ((plus +) (mult *))
ketos(>      (define ten (mult (plus 3 2) 2)))
ten
ketos=> ten
10
```

**Comment by Wulfsta** [comment]
So `let` can only take two arguments? I apologize for misinterpreting the syntax! Is there any way around this behavior? I'd like to feed in something akin to one of Rust's block expressions.

**Comment by murarth** [comment]
The `do` operator is what you're looking for. It evaluates a series of expressions and yields the value of the final expression.

**Comment by Wulfsta** [comment]
Thanks!
